Myproject/Myapp/urls.py
from . import views
from django.urls import path
app_name="Myapp"
urlpatterns = [
    path('', views.index, name="index"),
    path('learn', views.learn ,name="learn"),
    path('codeform', views.codeform, name="codeform"),
    path('pro', views.pro ,name="pro"),
    path('compare', views.compare,name="compare"),
]

Myproject/Myproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('Myapp.urls', namespace="Myapp")),
    path('s_parser/', include('s_parser.urls')),
    path('admin/', admin.site.urls),
]

Myproject/Myapp/models.py
from django.db import models

class Data(models.Model):
    seq = models.IntegerField(primary_key=True,blank=True)
    keywords = models.CharField(max_length=128,null=True,blank=True)
    entities = models.CharField(max_length=128,null=True,blank=True)
    categories = models.CharField(max_length=256, null=True,blank=True)
    desc = models.TextField(null=True,blank=True)
    source = models.TextField(null=True,blank=True)
    method = models.CharField(max_length=256, null=True,blank=True)
    check = models.TextField(null=True,blank=True)
    etc = models.TextField(null=True,blank=True)

    def __str__(self):
        return self.keywords

class CompareSource(models.Model):
    java = models.TextField(null=True, blank=True)
    class Meta:
        app_label='compareSource'

Myproject/Myapp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import Data
from django.views.decorators.csrf import csrf_exempt,csrf_protect
import json
from django.http import HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from ibm_watson import NaturalLanguageUnderstandingV1
from ibm_watson.natural_language_understanding_v1 import Features, EntitiesOptions, KeywordsOptions
from ibm_cloud_sdk_core.authenticators import IAMAuthenticator
from nltk.tokenize import sent_tokenize, word_tokenize

source_catch_lists = []
pattern = ""

def index(request):
    return render(request, 'templates/index.html')

source = ''
Content = {
    'keywords': {
        'text': [],
        'score': []
    },
    'entities': {
        'text': [],
        'score': []
    },
    'categories': {
        'text': [],
        'score': []
    },
}
semantic_roles = []



def learn(request):
    """
    natural_language_understanding = NaturalLanguageUnderstandingV1(
        version='2019-07-12',
        iam_apikey='FZxffQMR704hKD0dgFXEC8T0L0FFkhWzNImrOWPG6ZVh',
        url='https://gateway.watsonplatform.net/natural-language-understanding/api'
    )
    """
    try:
        authenticator = IAMAuthenticator('FZxffQMR704hKD0dgFXEC8T0L0FFkhWzNImrOWPG6ZVh')
        natural_language_understanding = NaturalLanguageUnderstandingV1(
            version='2019-07-12',
            authenticator=authenticator
        )
        natural_language_understanding.set_service_url('https://gateway.watsonplatform.net/natural-language-understanding/api')

    except expression as identifier:
        print("Watson Api connection error!")

    textinput = request.POST.get('a')

    """Catch the code line!!!"""
    # Python program for KMP Algorithm 
    def KMPSearch(pat, txt): 
        M = len(pat) 
        N = len(txt) 
    
        # create lps[] that will hold the longest prefix suffix  
        # values for pattern 
        lps = [0]*M 
        j = 0 # index for pat[] 
    
        # Preprocess the pattern (calculate lps[] array) 
        computeLPSArray(pat, M, lps) 
    
        i = 0 # index for txt[] 
        while i < N: 
            if pat[j] == txt[i]: 
                i += 1
                j += 1
    
            if j == M: 
                print ("Found pattern at index"+str(i-j))
                source_catch_lists.append(txt)
                print(source_catch_lists)
                j = lps[j-1] 
    
            # mismatch after j matches 
            elif i < N and pat[j] != txt[i]: 
                # Do not match lps[0..lps[j-1]] characters, 
                # they will match anyway 
                if j != 0: 
                    j = lps[j-1] 
                else: 
                    i += 1
    
    def computeLPSArray(pat, M, lps): 
        len = 0 # length of the previous longest prefix suffix 
    
        lps[0] # lps[0] is always 0 
        i = 1
    
        # the loop calculates lps[i] for i = 1 to M-1 
        while i < M: 
            if pat[i]== pat[len]: 
                len += 1
                lps[i] = len
                i += 1
            else: 
                # This is tricky. Consider the example. 
                # AAACAAAA and i = 7. The idea is similar  
                # to search step. 
                if len != 0: 
                    len = lps[len-1] 
    
                    # Also, note that we do not increment i here 
                else: 
                    lps[i] = 0
                    i += 1
    
    #input all languages functions/methods name here
    pattern = "getParameter"

    for i in sent_tokenize(textinput): 
        KMPSearch(pattern, i)
    """Catch the code line!!! end"""


    response = natural_language_understanding.analyze(
        text=textinput,
        features=Features(
            entities=EntitiesOptions(
               emotion=False,
            ),
            categories=EntitiesOptions(
                emotion=False,
            ),
            semantic_roles=EntitiesOptions(
                emotion=False,
                sentiment=False,
            ),
            keywords=KeywordsOptions(
                emotion=False,
                sentiment=False,
            )
        )
    )

    re = response

    semantic_roles.append(json.dumps(re.result['semantic_roles'][0]['sentence']))
    for h in ['keywords','entities','categories']:
        for i in re.result[h]:
            try:
                try:
                    if (float(json.dumps(i['relevance'])) > 0.3):
                        Content[h]['text'].append(i['text'])
                        Content[h]['score'].append(i['relevance'])
                    else:
                        pass
                except:
                    if (float(json.dumps(i['relevance'])) > 0.3):
                        Content[h]['text'].append(i['label'])
                        Content[h]['score'].append(i['relevance'])
                    else:
                        pass
            except:
                try:
                    if (float(json.dumps(i['score'])) > 0.3):
                        Content[h]['text'].append(i['text'])
                        Content[h]['score'].append(i['score'])
                    else:
                        pass
                except:
                    if (float(json.dumps(i['score'])) > 0.3):
                        Content[h]['text'].append(i['label'])
                        Content[h]['score'].append(i['score'])
                    else:
                        pass

    count = Data.objects.count()
    count = count + 1
    data = Data(seq=count, keywords=Content['keywords']['text'][0], entities=Content['entities']['text'],
                categories=Content['categories']['text'],
                desc=semantic_roles[0].__str__().split('"'), source=source_catch_lists, method=pattern, etc='')
    data.save()
    print("saved!")
    reset(Content)
    cont = request.POST.get('a')
    return HttpResponse(source(cont))

def db_compare(comparesource):
    conn = pymysql.connect(host='localhost', user='secugo', password='password', db='test1', charset='utf8')
    curs = conn.cursor(pymysql.cursors.DictCursor)
    sql = "select * from test"
    number_of_rows = curs.execute(sql)
    rows = curs.fetchall()
    keysource = []
    num = 0
    a = comparesource.split('\n')

    for i in range(number_of_rows):
        keysource.insert(num,rows[i]['keysource'])
        num+=1

    for i in keysource:
        for k in range(number_of_rows):
            if(rows[k]["keysource"]==i):
                rownum = k

        for j in a:
            fin = j.find(i)

            if(fin != -1):
                result = str(a.index(j)+1)+"번 째 줄 "+"\n" + j +"\n"\
                +"keyword= "+str(rows[rownum]["keyword"])+"\n"\
                + "category= "+str(rows[rownum]["category"])+"\n"\
                +"description= "+str(rows[rownum]["description"])+"\n"\
                +"url= " + str(rows[rownum]["url"])+"\n"\
                +"source= "+str(rows[rownum]["source"])+"\n"\
                +"keysource= " + str(rows[rownum]["keysource"])

            else:
                continue

    return result


def sync(comparesource):
    fin = comparesource.find('request.getParameter')
    first = comparesource.find('String')
    end = comparesource.find(';',fin)
    a =''
    for i in range(first,end) :
        a +=comparesource[i]

    return  a


def reset(Content):
    for h in ['keywords', 'entities', 'categories']:
        Content[h]['text'].clear()
        Content[h]['score'].clear()
    semantic_roles.clear()



def source(te):
    re = []
    return te.split(";")[0]


def codeform(request):
    return render(request, 'templates/tem.html')


def compare(request):
    data = request.GET['text']
    return render(request, 'templates/comparecode.html',{"source" : db_compare(data)})


def pro(request):
    return render(request, 'templates/tem.html')

Myproject/Myapp/templates/comparecode.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

</head>
<body>
    <h1 id ="compare"> {{source}}</h1>

</body>
</html>

Myproject/Myapp/templates/index.html
<!DOCTYPE html>
<html lang="ko">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>SecuGo - Neural Learning Vulnerability Machine</title>

  <!-- Bootstrap core CSS -->
  <link href="/static/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- Custom fonts for this template -->
  <link href="/static/vendor/fontawesome-free/css/all.min.css" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="/static/css/grayscale.min.css" rel="stylesheet">
  <style>
    /* Google Fonts */
    @import url(https://fonts.googleapis.com/css?family=Anonymous+Pro);

    body{
      color: rgba(255,255,255,.75);
      font-family: 'Anonymous Pro', monospace;  
    }
    .css-typing p {
      border-right: .15em solid orange;
      font-family: "Courier";
      font-size: 14px;
      white-space: nowrap;
      overflow: hidden;
    }
    .css-typing p:nth-child(1) {
      width: 4em;
      -webkit-animation: type 2s steps(80, end);
      animation: type 2s steps(40, end);
      -webkit-animation-fill-mode: forwards;
      animation-fill-mode: forwards;
    }

    .css-typing p:nth-child(2) {
      width: 11.5em;
      opacity: 0;
      -webkit-animation: type2 2s steps(40, end);
      animation: type2 2s steps(40, end);
      -webkit-animation-delay: 2s;
      animation-delay: 2s;
      -webkit-animation-fill-mode: forwards;
      animation-fill-mode: forwards;
    }

    .css-typing p:nth-child(3) {
      width: 11.5em;
      opacity: 0;
      -webkit-animation: type3 2s steps(40, end), blink .5s step-end infinite alternate;
      animation: type3 2s steps(40, end), blink .5s step-end infinite alternate;
      -webkit-animation-delay: 4s;
      animation-delay: 4s;
      -webkit-animation-fill-mode: forwards;
      animation-fill-mode: forwards;
    }

    @keyframes type {
      0% {
        width: 0;
      }
      99.9% {
        border-right: .15em solid orange;
      }
      100% {
        border: none;
      }
    }

    @-webkit-keyframes type {
      0% {
        width: 0;
      }
      99.9% {
        border-right: .15em solid orange;
      }
      100% {
        border: none;
      }
    }

    @keyframes type2 {
      0% {
        width: 0;
      }
      1% {
        opacity: 1;
      }
      99.9% {
        border-right: .15em solid orange;
      }
      100% {
        opacity: 1;
        border: none;
      }
    }

    @-webkit-keyframes type2 {
      0% {
        width: 0;
      }
      1% {
        opacity: 1;
      }
      99.9% {
        border-right: .15em solid orange;
      }
      100% {
        opacity: 1;
        border: none;
      }
    }

    @keyframes type3 {
      0% {
        width: 0;
      }
      1% {
        opacity: 1;
      }
      100% {
        opacity: 1;
      }
    }

    @-webkit-keyframes type3 {
      0% {
        width: 0;
      }
      1% {
        opacity: 1;
      }
      100% {
        opacity: 1;
      }
    }

    @keyframes blink {
      50% {
        border-color: transparent;
      }
    }
    @-webkit-keyframes blink {
      50% {
        border-color: tranparent;
      }
    }
  </style>
</head>

<body id="page-top">

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand js-scroll-trigger" href="#page-top">SecuGo</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#about">About</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#projects">Feature</a>
          </li>
          <li class="nav-item">
            <a class="nav-link js-scroll-trigger" href="#signup">Contact</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Header -->
  <header class="masthead">
    <div class="container d-flex h-100 align-items-center">
      <div class="mx-auto text-center">
        <!--<h1 class="mx-auto my-0">SecuGo</h1>-->
        
        <div class="css-typing text-center">
          <p style="font-size:30px">SecuGo</p>
          <p>For Secure Coding</p>
          <p>And Code Analysis</p>
        </div>
                
        <h2 class="text-white-50 mx-auto mt-2 mb-5">
          onliine code checking tool<br/> based on IBM Watson API.
        </h2>
        <a href="{% url 'Myapp:codeform' %}" class="btn btn-primary js-scroll-trigger">Get Started</a>
      </div>
    </div>
  </header>

  <!-- About Section -->
  <section id="about" class="about-section text-center">
    <div class="container">
      <div class="row">
        <div class="col-lg-8 mx-auto">
          <img src="https://user-images.githubusercontent.com/28107452/49039284-b37d7480-f202-11e8-81b6-f041ebd3351a.png" style="width:100%">
          <p class="text-white-50"></p>
          <p>
            As security threats increase, the importance of "secure-coding" has grown.
            According to the IBM X-Force Tech report, 41% of new vulnerabilities occur in web applications. In addition, vulnerabilities such as known XSS and SQL injection continue to grow.
            Companies and developers have found vulnerabilities in code development through code review and simulation.
            However, it takes a lot of time, so many companies are now benefiting from the use of automated tools.
          </p>
          <p>
            The problem with our team is that the "test case" used in simulation and automation tools is being updated manually.
            With the advent of automation tools, the "test case," which is the basis for diagnosing, has caused a gap between the occurrence of security incidents and the reflection on the source code.
            To address this, Secugo will creates a "test case."
          </p>
            Secugo is Powered by <a href="https://www.ibm.com/watson/kr-ko/developercloud/natural-language-understanding.html">Watson NLU API</a></p>
        </div>
      </div>
      <img src="img/ipad.png" class="img-fluid" alt="">
    </div>
  </section>

  <!-- Projects Section -->
  <section id="projects" class="projects-section bg-light">
    <div class="container">

      <!-- Featured Project Row -->
      <div class="row align-items-center no-gutters mb-4 mb-lg-5">
        <div class="col-xl-5 col-lg-6">
          <div class="featured-text text-center text-lg-left">
            <p class="text-black-50 mb-0">Enhancements can be made later on..</p>
          </div>
        </div>
      </div>

      <!-- Project One Row -->
      <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
        <div class="col-lg-6">
          <img class="img-fluid" src="img/demo-image-01.jpg" alt="">
        </div>
        <div class="col-lg-6">
          <div class="bg-black text-center h-100 project">
              <div class="project-text w-100 my-auto text-center text-lg-left">
                <h4 class="text-white">Code Vulnerability Check</h4>
                <br/>
                <p class="mb-0 text-white-50">
                <img src="static/img/intro.png" style="width:100%">
                <ul>
                <br/>
                  <li>Collect incident cases from security case sites such as CWE,ANS,OWASP</li>
                  <li>Perform a custom NLU, transform the data into categorised security data.</li>
                  <li>Subsequently, pattern matching is used to compare all source codes and the above cases shown in Github.</li>
                </ul>
                </p>
                <hr class="d-none d-lg-block mb-0 ml-0">
              </div>
            </div>
          </div>
        </div>
      </div>
    
    <div class="container">
      <!-- Project Two Row -->
      <div class="row justify-content-center no-gutters">
        <div class="col-lg-6">
          <img class="img-fluid" src="img/demo-image-02.jpg" alt="">
        </div>
        <div class="col-lg-6 order-lg-first">
          <div class="bg-black text-center h-100 project">
            <div class="d-flex h-100">
              <div class="project-text w-100 my-auto text-center text-lg-right">
                <h4 class="text-white">NLU Analysis</h4>
                <p class="mb-0 text-white-50">
                  <img src="static/img/nlu.jpg" style="width:100%"><br/>
                  <br/>When given a any random text, <br/>
                  SecuGo will analyze the natural language <br/>and return the analytic report.<br/>
                  you can try more examples in 
                  <a href="https://natural-language-understanding-demo.ng.bluemix.net/?_ga=2.9579379.756537875.1569062926-36951928.1568789315&cm_mc_uid=71980874898015550801110&cm_mc_sid_50200000=62483451569066611293&cm_mc_sid_52640000=87940991569066611311">
                  Watson API demo page</a> 

                </p>
                <hr class="d-none d-lg-block mb-0 mr-0">
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
  </section>

  <!-- Signup Section -->
  <section id="signup" class="signup-section">
    <div class="container">
      <div class="row">
        <div class="col-md-10 col-lg-8 mx-auto text-center">

          <i class="far fa-envelope fa-2x mb-2 text-white"></i>
          <h2 class="text-white mb-5">Subscribe to receive updates!</h2>

          <form class="form-inline d-flex">
            <input type="email" class="form-control flex-fill mr-0 mr-sm-2 mb-3 mb-sm-0" id="inputEmail" placeholder="Enter email address...">
            <button type="submit" class="btn btn-primary mx-auto">Subscribe</button>
          </form>

        </div>
      </div>
    </div>
  </section>

  <!-- Contact Section -->
  <section class="contact-section bg-black">
    <div class="container">

      <div class="row">

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-map-marked-alt text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Address</h4>
              <hr class="my-4">
              <div class="small text-black-50">4923 Market Street, Orlando FL</div>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-envelope text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Email</h4>
              <hr class="my-4">
              <div class="small text-black-50">
                <a href="#">hello@yourdomain.com</a>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4 mb-3 mb-md-0">
          <div class="card py-4 h-100">
            <div class="card-body text-center">
              <i class="fas fa-mobile-alt text-primary mb-2"></i>
              <h4 class="text-uppercase m-0">Phone</h4>
              <hr class="my-4">
              <div class="small text-black-50">+1 (555) 902-8832</div>
            </div>
          </div>
        </div>
      </div>

      <div class="social d-flex justify-content-center">
        <a href="#" class="mx-2">
          <i class="fab fa-twitter"></i>
        </a>
        <a href="#" class="mx-2">
          <i class="fab fa-facebook-f"></i>
        </a>
        <a href="#" class="mx-2">
          <i class="fab fa-github"></i>
        </a>
      </div>

    </div>
  </section>

  <!-- Footer -->
  <footer class="bg-black small text-center text-white-50">
    <div class="container">
      Copyright &copy; SecuGo 2019
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="/static/vendor/jquery/jquery.min.js"></script>
  <script src="/static/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  <!-- Plugin JavaScript -->
  <script src="/static/vendor/jquery-easing/jquery.easing.min.js"></script>

  <!-- Custom scripts for this template -->
  <script src="/static/js/grayscale.min.js"></script>
</body>

</html>

Myproject/Myapp/templates/pro.html
<!DOCTYPE html>
<html lang="en">

<body>
    {{count}}
</body>
</html>

Myproject/Myapp/templates/tem.html
<!DOCTYPE html>
<html lang="en">
<body>
    <form>
        {% csrf_token %}
        <br>
        <textarea id="text" name=text COLS=100 ROWS=20></textarea>
        <br>
        <input type="button" value="learning" id="learnbtn" />
        <input type="button" value="codecheck" id="combtn" />
        <br>
        <h1 id="a"  ></h1><br>
        <p id="content">
    </form>
</body>
<script src="http://code.jquery.com/jquery-1.11.2.min.js"></script>
<script src="http://code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script type="text/javascript" language="javascript">
    $("#combtn").on("click", function () {
       var form = document.createElement('form');
       var obj = document.createElement('input');
       obj.setAttribute('name','text');
       obj.setAttribute('type','hidden');
       obj.setAttribute('value',$('#text').val());
       form.setAttribute('method','get');
       form.setAttribute('action','{% url "Myapp:compare" %}');
       form.appendChild(obj);
       document.body.appendChild(form);
       form.submit();

    });
    $("#learnbtn").on("click", function(){
        var csrftoken = $("[name=csrfmiddlewaretoken]").val();
        function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
        return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }

        $.ajaxSetup({
        beforeSend: function(xhr, settings) {
            if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                xhr.setRequestHeader("X-CSRFToken", csrftoken);
            }
        }
        });
        var con = $('#text').val()
        $.ajax({
              type: "post",
              url: "learn",
              data: {
                  'a' : con
              },
              dataType: "text",
              success: function (response) {
                  $("#text").text('');
                  $("#a").text(response);
              }
          });
      });
</script>
</html>